-- Add up migration script here
CREATE TABLE resources (
    id UUID PRIMARY KEY NOT NULL DEFAULT uuidv7(),
    username VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    config VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);